API provides functionality for user to add products to current order
CraftAcademy/slowfood-api-team-1-april-2020 pull request #4
Opened 2020-05-09 10:23 UTC by PaulineBA

## [PT LINK]( https://www.pivotaltracker.com/story/show/172716504)
### User Story
```As a restaurant API
In order for users to buy food they want from the restaurant
I would like them to be able to add multiple products to an order for a specific user
```
## Changes proposed in this pull request:
Editing the Orders Controller, the routes and the spec file.

## What I have learned working on this feature:
* We learned how to create Update action in the controller.
* We need to always declare a method in the test before calling on them

2020-05-09 10:34 UTC, jysmys approved these changes
Looks good to me, just one small intention!

2020-05-09 10:34 UTC, jysmys commented on app/controllers/api/v1/orders_controller.rb
> +end
tab it in one step...

2020-05-09 11:56 UTC, erikbjoern reviewed
The PR and request spec should be called order_controller_spec.

2020-05-09 11:57 UTC, erikbjoern requested changes
The request spec should be called orders_controller_spec or something with create / update I think.

2020-05-10 17:50 UTC, erikbjoern approved these changes

2020-05-10 17:50 UTC, merged